# Generated by Django 6.0 on 2026-04-20 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("production_record", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LotTraceability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "history_snapshot",
                    models.JSONField(
                        help_text="Copia de seguridad inalterable de los datos de producción."
                    ),
                ),
                ("integrity_hash", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "production_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traceability_record",
                        to="production_record.productionorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expediente de Trazabilidad",
                "verbose_name_plural": "Expedientes de Trazabilidad",
            },
        ),
    ]
