# Generated by Django 6.0 on 2026-04-17 13:54

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WineAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_date", models.DateField(verbose_name="Fecha de Análisis")),
                (
                    "laboratory",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Laboratorio/Analista"
                    ),
                ),
                (
                    "alcohol_content",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("22.00")),
                        ],
                        verbose_name="Grado Alcohólico (% vol)",
                    ),
                ),
                (
                    "volatile_acidity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("2.00")),
                        ],
                        verbose_name="Acidez Volátil (g/L)",
                    ),
                ),
                (
                    "total_acidity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.00")),
                            django.core.validators.MaxValueValidator(Decimal("15.00")),
                        ],
                        verbose_name="Acidez Total (g/L)",
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("2.50")),
                            django.core.validators.MaxValueValidator(Decimal("4.50")),
                        ],
                        verbose_name="pH",
                    ),
                ),
                (
                    "reducing_sugars",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("300.00")),
                        ],
                        verbose_name="Azúcares Reductores (g/L)",
                    ),
                ),
                (
                    "malic_acid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("10.00")),
                        ],
                        verbose_name="Ácido Málico (g/L)",
                    ),
                ),
                (
                    "lactic_acid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("10.00")),
                        ],
                        verbose_name="Ácido Láctico (g/L)",
                    ),
                ),
                (
                    "IC",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("50.00")),
                        ],
                        verbose_name="indice Colorante",
                    ),
                ),
                (
                    "folin_index",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("150.00")),
                        ],
                        verbose_name="Índice de Folin (IPT)",
                    ),
                ),
                (
                    "gluconic_acid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("10.00")),
                        ],
                        verbose_name="Ácido Glucónico (g/L)",
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Análisis Enológico",
                "verbose_name_plural": "Análisis Enológicos",
                "ordering": ["-analysis_date", "-created_at"],
            },
        ),
    ]
