# Generated by Django 6.0 on 2026-04-17 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("production_record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wineanalysis",
            name="production_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="production_record.productionorder",
                verbose_name="Orden de Producción",
            ),
        ),
    ]
