# Generated by Django 6.0 on 2026-04-17 13:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre único de la categoría de suministro.",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre comercial o razón social completa.",
                        max_length=200,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        help_text="Identificación fiscal única (NIF/CIF).",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El NIF/CIF debe tener 9 caracteres y un formato válido (ej: A1234567B).",
                                regex="^[A-Z0-9][0-9]{7}[A-Z0-9]$",
                            )
                        ],
                    ),
                ),
                (
                    "supplier_code",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "email_pedidos",
                    models.EmailField(
                        max_length=254,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Introduce un email corporativo válido."
                            )
                        ],
                        verbose_name="email de pedidos",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Teléfono con prefijo internacional.",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El teléfono debe incluir prefijo internacional (ej: +34600123123) y tener entre 9 y 15 dígitos.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="dirección física"),
                ),
                (
                    "lead_time",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Días promedio desde pedido a entrega.",
                        verbose_name="días de entrega",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suppliers",
                        to="supplier.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",),
                        name="unique_supplier_name_case_insensitive",
                        violation_error_message="Ya existe un proveedor con este nombre.",
                    )
                ],
            },
        ),
    ]
