# Generated by Django 6.0 on 2026-03-25 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("tax_id", models.CharField(max_length=20, unique=True)),
                (
                    "supplier_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "email_pedidos",
                    models.EmailField(max_length=254, verbose_name="email de pedidos"),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                (
                    "lead_time",
                    models.PositiveIntegerField(
                        default=7, help_text="Días promedio de entrega"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suppliers",
                        to="supplier.category",
                    ),
                ),
            ],
        ),
    ]
