# Generated by Django 6.0 on 2026-03-25 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name": "Proveedor", "verbose_name_plural": "Proveedores"},
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Nombre único de la categoría de suministro.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.TextField(blank=True, verbose_name="dirección física"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="email_pedidos",
            field=models.EmailField(
                max_length=254,
                validators=[
                    django.core.validators.EmailValidator(
                        message="Introduce un email corporativo válido."
                    )
                ],
                verbose_name="email de pedidos",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="lead_time",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Días promedio desde pedido a entrega.",
                verbose_name="días de entrega",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(
                help_text="Nombre comercial o razón social completa.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Teléfono con prefijo internacional.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El teléfono debe incluir prefijo internacional (ej: +34600123123) y tener entre 9 y 15 dígitos.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_code",
            field=models.CharField(
                db_index=True, editable=False, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="tax_id",
            field=models.CharField(
                help_text="Identificación fiscal única (NIF/CIF).",
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El NIF/CIF debe tener 9 caracteres y un formato válido (ej: A1234567B).",
                        regex="^[A-Z0-9][0-9]{7}[A-Z0-9]$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                fields=("name",),
                name="unique_supplier_name_case_insensitive",
                violation_error_message="Ya existe un proveedor con este nombre.",
            ),
        ),
    ]
