# Usamos una imagen ligera de Node
FROM node:22-bookworm-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiamos los archivos de dependencias primero para aprovechar la caché
COPY package.json package-lock.json ./

# Instalamos las dependencias
RUN npm install

# Copiamos el resto del código del frontend
COPY . .

# Exponemos el puerto por defecto de Vite
EXPOSE 5173

# Comando para arrancar en modo desarrollo
# El flag --host es CRUCIAL para que Docker mapee el puerto hacia afuera
CMD ["npm", "run", "dev", "--", "--host"]