services:
  client:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - client-db
  client-db:
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/postgresql/
    environment:
      - POSTGRES_USER=client
      - POSTGRES_PASSWORD=client
      - POSTGRES_DB=client_dev
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules # Volumen anónimo para proteger librerías internas
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=http://localhost:8009/api/
    stdin_open: true
    tty: true
    depends_on:
      - client
volumes:
  postgres_data: