# Generated by Django 6.0 on 2026-06-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="batch_number",
            field=models.CharField(max_length=50, verbose_name="Número de Lote"),
        ),
    ]
