# Generated by Django 6.0 on 2026-06-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_alter_batch_batch_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="current_stock_cache",
            field=models.DecimalField(
                decimal_places=3,
                default=0.0,
                max_digits=12,
                verbose_name="Existencias Vivas (Caché)",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="stock_status",
            field=models.CharField(
                choices=[("AVAILABLE", "En Existencias"), ("DEPLETED", "Agotado")],
                db_index=True,
                default="AVAILABLE",
                max_length=50,
                verbose_name="Estado Operativo",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("IN", "Entrada (Compra/Producción)"),
                    ("OUT", "Salida (Venta/Uso)"),
                    ("ADJ", "Ajuste de Inventario"),
                    ("TRANS_OUT", "Salida por Transferencia"),
                    ("TRANS_IN", "Entrada por Transferencia"),
                ],
                max_length=10,
            ),
        ),
    ]
