# Generated by Django 6.0 on 2026-04-27 07:07

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("production_record", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndirectCostConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ej: Tasas Generales 2026", max_length=100
                    ),
                ),
                (
                    "labor_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000")),
                            django.core.validators.MaxValueValidator(Decimal("1.0000")),
                        ],
                    ),
                ),
                (
                    "energy_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000")),
                            django.core.validators.MaxValueValidator(Decimal("1.0000")),
                        ],
                    ),
                ),
                (
                    "amortization_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.0000"),
                                django.core.validators.MaxValueValidator(
                                    Decimal("1.0000")
                                ),
                            )
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Solo puede haber una activa a la vez"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Configuración de Costos Indirectos",
            },
        ),
        migrations.CreateModel(
            name="ProductionCosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("materials_snapshot", models.JSONField()),
                ("labor_total", models.DecimalField(decimal_places=4, max_digits=12)),
                ("energy_total", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "amortization_total",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                (
                    "total_material_cost",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                (
                    "total_indirect_cost",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                ("grand_total", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Costo total / unidades producidas",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "production_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costing_record",
                        to="production_record.productionorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escandallo de Producción",
            },
        ),
    ]
