# Generated by Django 6.0 on 2026-04-17 13:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("wines", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "production_date",
                    models.DateField(verbose_name="Fecha de Embotellado"),
                ),
                (
                    "quantity_produced",
                    models.PositiveIntegerField(
                        help_text="Cantidad total de unidades finalizadas (botellas, BIB, etc.)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        help_text="Código de lote impreso en el envase (ej: L24-001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Lote de Producto Terminado",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("CONFIRMED", "Confirmado (Stock descontado)"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "bulk_liters_withdrawn",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Cantidad real de vino líquido que salió del depósito según caudalímetro.",
                        max_digits=12,
                        verbose_name="Litros extraídos de depósito",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_orders",
                        to="wines.winemodel",
                        verbose_name="Vino a Embotellar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parte de Embotellado",
                "verbose_name_plural": "Partes de Embotellado",
                "ordering": ["-production_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionEnologicalItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_used",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Cantidad total usada en todo el lote de producción",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.enologicalmaterialmodel",
                        verbose_name="Producto Enológico",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enological_materials",
                        to="production_record.productionorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insumo Enológico Usado",
                "unique_together": {("production_order", "material")},
            },
        ),
    ]
