# Generated by Django 6.0 on 2026-04-17 13:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnologicalMaterialModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Nombre del Material"
                    ),
                ),
                (
                    "internal_code",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Código Interno",
                    ),
                ),
                (
                    "unit_mesure",
                    models.CharField(
                        choices=[
                            ("UNIDAD", "Unidades"),
                            ("KG", "Kilogramos"),
                            ("LITRO", "Litros"),
                            ("MILLAR", "Millares"),
                        ],
                        default="UNIDAD",
                        max_length=10,
                        verbose_name="Unidad de Medida",
                    ),
                ),
                (
                    "min_stock_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Stock Mínimo de Seguridad",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="¿Está activo?"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción Técnica"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enological_type",
                    models.CharField(
                        choices=[
                            (
                                "ESTABILIZANTE",
                                "Estabilizantes (Goma Arábiga, Manoproteínas,antartika)",
                            ),
                            ("CONSERVANTE", "Conservantes (Sulfitos, Ascórbico)"),
                            ("ACIDIFICANTE", "Acidificantes y Correctores"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Producto",
                    ),
                ),
                (
                    "commercial_format",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Saco 25kg, Garrafa 20L, Sobre 500g",
                        max_length=50,
                        verbose_name="Formato de Envase",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_materials",
                        to="supplier.supplier",
                        verbose_name="Proveedor Habitual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto Enológico",
                "verbose_name_plural": "Productos Enológicos",
            },
        ),
        migrations.CreateModel(
            name="LabelMaterialModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Nombre del Material"
                    ),
                ),
                (
                    "internal_code",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Código Interno",
                    ),
                ),
                (
                    "unit_mesure",
                    models.CharField(
                        choices=[
                            ("UNIDAD", "Unidades"),
                            ("KG", "Kilogramos"),
                            ("LITRO", "Litros"),
                            ("MILLAR", "Millares"),
                        ],
                        default="UNIDAD",
                        max_length=10,
                        verbose_name="Unidad de Medida",
                    ),
                ),
                (
                    "min_stock_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Stock Mínimo de Seguridad",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="¿Está activo?"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción Técnica"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label_type",
                    models.CharField(
                        choices=[
                            ("FRONTAL", "Etiqueta Frontal"),
                            ("CONTRA", "Contraetiqueta"),
                            ("COLLARIN", "Collarín/Cápsula de papel"),
                            ("TIRILLA", "Precinto de Garantía / Tirilla D.O."),
                            ("MEDALLA", "Adhesivo Medalla/Premios"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Etiqueta",
                    ),
                ),
                (
                    "brand_reference",
                    models.CharField(
                        help_text="Ej: Reserva de la Familia, Crianza, Blanco Joven",
                        max_length=100,
                        verbose_name="Marca de la Bodega",
                    ),
                ),
                (
                    "vintage",
                    models.PositiveIntegerField(
                        help_text="Año de la cosecha ",
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Añada",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_materials",
                        to="supplier.supplier",
                        verbose_name="Proveedor Habitual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etiqueta/Contra",
                "verbose_name_plural": "Etiquetas y Contras",
            },
        ),
        migrations.CreateModel(
            name="PackagingMaterialModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Nombre del Material"
                    ),
                ),
                (
                    "internal_code",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Código Interno",
                    ),
                ),
                (
                    "unit_mesure",
                    models.CharField(
                        choices=[
                            ("UNIDAD", "Unidades"),
                            ("KG", "Kilogramos"),
                            ("LITRO", "Litros"),
                            ("MILLAR", "Millares"),
                        ],
                        default="UNIDAD",
                        max_length=10,
                        verbose_name="Unidad de Medida",
                    ),
                ),
                (
                    "min_stock_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Stock Mínimo de Seguridad",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="¿Está activo?"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción Técnica"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "packaging_type",
                    models.CharField(
                        choices=[
                            ("VIDRIO", "Vidrio (Botellas)"),
                            ("BIB", "BAG IN BOX"),
                            ("PLASTICO", "GARRAFA / PET"),
                            ("CIERRE", "Cierres (Corchos/Tapones/Rosca)"),
                            ("CAPSULA", "Cápsulas"),
                            ("ETIQUETA", "Etiquetado (Frontal/Contra/Tirilla)"),
                            ("EMBALAJE", "Embalaje Seco (Cajas/Separadores)"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Material",
                    ),
                ),
                (
                    "specification",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 75cl, 1.5L, Caja 6 bot, Corcho 44x24mm",
                        max_length=100,
                        verbose_name="Especificación técnica",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Solo para vidrio y botellas",
                        max_length=50,
                    ),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Capacidad en litros. Solo para botellas, BIB, etc.",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_materials",
                        to="supplier.supplier",
                        verbose_name="Proveedor Habitual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material de Acondicionamiento",
                "verbose_name_plural": "Materiales de Acondicionamiento",
            },
        ),
    ]
