# Generated by Django 6.0 on 2026-03-27 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labelmaterialmodel",
            name="vintage",
            field=models.PositiveIntegerField(
                help_text="Año de la cosecha ",
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2100),
                ],
                verbose_name="Añada",
            ),
        ),
    ]
