# Generated by Django 6.0 on 2026-04-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagingmaterialmodel",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Solo para vidrio y botellas",
                max_length=50,
                null=True,
            ),
        ),
    ]
