# Generated by Django 6.0 on 2026-03-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_labelmaterialmodel_vintage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagingmaterialmodel",
            name="packaging_type",
            field=models.CharField(
                choices=[
                    ("VIDRIO", "Vidrio (Botellas)"),
                    ("BIB", "BAG IN BOX"),
                    ("PLASTICO", "GARRAFA / PET"),
                    ("CIERRE", "Cierres (Corchos/Tapones/Rosca)"),
                    ("CAPSULA", "Cápsulas"),
                    ("ETIQUETA", "Etiquetado (Frontal/Contra/Tirilla)"),
                    ("EMBALAJE", "Embalaje Seco (Cajas/Separadores)"),
                ],
                max_length=20,
                verbose_name="Tipo de Material",
            ),
        ),
    ]
