# Generated by Django 6.0 on 2026-05-31 09:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_packagingmaterialmodel_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagingmaterialmodel",
            name="capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Capacidad en litros. Solo para botellas, BIB, etc.",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
    ]
