FROM python:3.12-slim-bookworm

# set working directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# new
# install system dependencies
COPY ./scripts/install_sys_deps.sh ./scripts/install_sys_deps.sh
RUN chmod +x ./scripts/install_sys_deps.sh && ./scripts/install_sys_deps.sh

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# add app
COPY . .

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]