"""
Django settings for drf_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get("SECRET_KEY")

DEBUG = int(os.environ.get("DEBUG", default=0))

# 'DJANGO_ALLOWED_HOSTS' should be a single string of hosts with a space between each.
# For example: 'DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]'
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS").split(" ")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    'rest_framework_simplejwt.token_blacklist',
    "drf_spectacular",
    "django_extensions",
    "corsheaders",

    "client",
    "supplier",
    "inventory",
    "wines",
    "purchase",
    "stock",
    "production_record",
    "analytics",
    "traceability",
    "pricing",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "drf_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "drf_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Abstract User
AUTH_USER_MODEL = "client.CustomUser"

# simple-jwt (Authentication)
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",  # Protege todos los endpoints por defecto
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "utils.pagination.StandardResultsSetPagination",
}

# Modificación de los tiempos por defecto

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    'BLACKLIST_AFTER_ROTATION': True,
    "AUTH_HEADER_TYPES": ("Bearer",),  # El prefijo que irá en el header de React
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Ontalba Bodega API",
    "DESCRIPTION": "Documentación técnica para la gestión de proveedores y suministros.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,  # No incluir el endpoint del esquema dentro del propio esquema (evita bucles).
    # Esta parte es vital para que el botón "Authorize" de Swagger funcione con JWT:
    "COMPONENT_SPLIT_REQUEST": True,
}

# Leemos la variable de entorno, si no existe, usamos localhost por defecto
CORS_ALLOWED_ORIGIN_VALUES = os.environ.get("CORS_ALLOWED_ORIGINS", "http://localhost:5173 http://127.0.0.1:5173")

# En desarrollo, React suele correr en el puerto 5173 (Vite) o 3000 (CRA)
CORS_ALLOWED_ORIGINS = CORS_ALLOWED_ORIGIN_VALUES.split(" ")

# CSRF: Permite que Django acepte peticiones POST/PUT desde estos dominios
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

# Si necesitas permitir que React envíe cookies o use autenticación por sesión/token:
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "accept",            # Permite a React decir qué formato espera (JSON)
    "authorization",     # Obligatorio: transporta el Token JWT (Bearer)
    "content-type",      # Obligatorio: indica que enviamos datos en JSON
    "origin",            # Informa al servidor desde qué dominio viene la web
    "user-agent",        # Envía info del navegador (útil para logs/seguridad)
    "x-csrftoken",       # Necesario si usas el sistema de Login/Sesión de Django
    "x-requested-with",  # Indica que es una petición AJAX (evita bloqueos antiguos)
]
# En caso de no poner la barra final redirecciona como si la hubiesemos puesto
APPEND_SLASH = True

CORS_PREFLIGHT_MAX_AGE = 86400