# Generated by Django 6.0 on 2026-03-30 09:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0003_alter_packagingmaterialmodel_packaging_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="WineModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "vintage",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "internal_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "appellation_type",
                    models.CharField(
                        choices=[
                            ("DOP", "DENOMINACIÓN DE ORIGEN PROTEGIDA"),
                            ("DOCa", "DENOMINACIÓN DE ORIGEN CALIFICADA"),
                            ("VP", "VINO DE PAGO"),
                            ("VC", "VINO DE CALIDAD CON INDICACIÓN GEOGRÁFICA"),
                            (
                                "IGP",
                                "INDICACIÓN GEOGRÁFICA PROTEGIDA (VINO DE LA TIERRA)",
                            ),
                            ("MESA", "VINO DE MESA"),
                        ],
                        max_length=5,
                    ),
                ),
                ("appellation_name", models.CharField(max_length=100)),
                (
                    "wine_type",
                    models.CharField(
                        choices=[
                            ("BLANCO", "BLANCO"),
                            ("TINTO", "TINTO"),
                            ("ROSADO", "ROSADO"),
                            ("ESPUMOSO", "ESPUMOSO"),
                            ("GENEROSO", "GENEROSO"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "aging_category",
                    models.CharField(
                        choices=[
                            ("JOVEN", "JOVEN / SIN CRIANZA"),
                            ("ROBLE", "ROBLE"),
                            ("CRIANZA", "CRIANZA"),
                            ("RESERVA", "RESERVA"),
                            ("GRAN_RESERVA", "GRAN RESERVA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("varietals", models.TextField()),
                (
                    "alcohol_percentage",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "default_back_label",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"label_type": "CONTRA"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wine_back_labels",
                        to="inventory.labelmaterialmodel",
                    ),
                ),
                (
                    "default_container",
                    models.ForeignKey(
                        limit_choices_to={
                            "packaging_type__in": ["VIDRIO", "BIB", "PLASTICO"]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wine_containers",
                        to="inventory.packagingmaterialmodel",
                        verbose_name="Envase Principal",
                    ),
                ),
                (
                    "default_cork",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"packaging_type": "CIERRE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wine_closures",
                        to="inventory.packagingmaterialmodel",
                        verbose_name="Cierre/Tapón",
                    ),
                ),
                (
                    "default_dop_seal",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"label_type": "TIRILLA"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wines_as_seal",
                        to="inventory.labelmaterialmodel",
                        verbose_name="Precinto / Tirilla DOP",
                    ),
                ),
                (
                    "default_front_label",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"label_type": "FRONTAL"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wine_front_labels",
                        to="inventory.labelmaterialmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-vintage", "name"],
                "unique_together": {("name", "vintage")},
            },
        ),
    ]
