# Generated by Django 6.0 on 2026-05-31 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_packagingmaterialmodel_capacity"),
        ("wines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="winemodel",
            name="default_capsule",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"packaging_type": "CAPSULA"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wine_capsules",
                to="inventory.packagingmaterialmodel",
                verbose_name="Cápsula",
            ),
        ),
    ]
