# Generated by Django 6.0 on 2026-03-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_customuser_employee_id_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="employee_id",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
    ]
